### ISSUE TITLE
【依頼】フリマアプリ挙動確認

### ISSUE THREAD

**Issue by matsu006007** [matsu006007/furima-33508#9]
# フリマアプリ URL
      https://furima-33508.herokuapp.com/

# Basic認証　ID　パスワード
　ID：admin
    Pass：2222

# 出品者用メルアド　パスワード
　mail：test6@gmail.com
    pass：666bbb

# 購入者用メルアド　パスワード
　mail：tarou@gmail.com
   pass：abc123

# 購入者用カードの番号・期限・セキュリティコード

　　　　　　　　番号；4242424242424242
    　　　　　　　期限：33年　3月
　セキュリティコード：123

**Comment by naru6117** [comment]
ご提出ありがとうございます！
挙動確認させて頂いたところ、以下の不備が見受けられましたので修正をお願いします！

### [修正依頼箇所]

- [x] **ログイン状態の出品者でも、売却済みの商品に対しては「編集・削除ボタン」が表示されないようにしましょう！**

修正ができましたら、以下の最終課題完了報告フォームを再度提出お願いします！
※新しいissueを作っていただく必要はありません
https://forms.gle/dYuR1wjeHepbEhU7A

**Comment by matsu006007** [comment]
上記の修正依頼を実行致しました。
ご確認お願い致します。

**Comment by mo1015** [comment]
再提出ありがとうございます！
挙動確認させて頂きましたが、全く問題ございませんでしたのでLGTMとさせて頂きます:tada:
おめでとうございます！
**※確認したのは必須機能のみで追加実装した機能については確認していません。
そのため追加機能を実装している場合は、正しく想定通りの挙動であるかご自身で再度確認をお願いいたします。**
